### ISSUE TITLE
🧱 Create base interface architecture

### ISSUE THREAD

**Issue by axel-eck** [epitech-mirroring/ArcadeShared#1]
As viewed in meeting the project will lay down on some interfaces that should cover all basic needs and prevents future breaking changes.

# Game Interface
The Game Interface will represent each future game. We defined the game as something that can, start, run and have a score, so the interface should have at least those functions.
The Game Interface may also need a function to link a game to an arcade instance.

# Arcade Interface
The arcade, even if handled in the group scope, has to have common functions.
The arcade will link games to graphic drivers in a “one way” connection from the game to the driver (There is an exception for bindings and event, but that's about it), so the arcade interface will need at least the same functions as an IDriver

# Driver Interface
A graphic driver interface (aka IDriver) is what will *interface* with each graphic library. It should accept three main things:
1. A display function that accepts a displayable object.
2. A function that flip a frame. (Flipping a frame shall be considered as the process of freezing the buffered frame, then displaying it on the screen and at last create a new **clean** buffered frame for future draws)
3. A function that binds event. Each graphic library will handle this in their own way, but a game is interactive at the core. Each game shall be able to bind callbacks to available keys that will be called when the graphic library receives the event.

# Entities, Sprites & Primitives
Entities and Primitives are both displayable object, so we have to create a parent interface for those both that has some getter for the position and the size.

## Primitives
For simpler future development, we define primitives as shapes that have a color. Moreover, many graphic library gives function to draw specific shapes, such as circle, square and/or triangles so we shall create such interfaces giving radius or sides length for example.

## Entities
Entities are a bit more complex whilst staying a displayable object. An entity has a sprite attached to it, but later we could add more information like material, opacity etc...

## Sprites
A Sprite has a function to get the image for the actual frame, but also a char and a color as a fallback for a library that can't draw images or if the image is not available.

# Images
Since each library defined its own image type, we shall create a base level representation of what an image really is. This interface shall have getters for size and path at least.

**Comment by Marius-P1** [comment]
Ok, my opinion:
- For Sprite, can't we call them "Entities" that will contain a Sprite class that will have a size, a sprite sheet, a corresponding character and all the other informations.

**Comment by axel-eck** [comment]
> Ok, my opinion:
> 
> * For Sprite, can't we call them "Entities" that will contain a Sprite class that will have a size, a sprite sheet, a corresponding character and all the other informations.

Thanks for the heads-up, for future update splitting entities and sprites can be helpful.

**Comment by Antoinegtir** [comment]
I agree with most of the things listed in the issue, here is another important part that we haven't mention yet:

- Error Handling

Provide error handling mechanisms to handle failures or exceptions when linking games to graphic drivers using IError that will probably contain a function to get the message of the error thrown + AError to implement thoses function and all the child classes for each error thrown.

**Comment by axel-eck** [comment]
We can only share interface so "AError" is not in our scope. But yes we could have an IError. We will see this at the tomorrow's meeting

**Comment by aimericdrk** [comment]
ok for me ?
